version: "3.1"

services:
    db:
        image: postgres
        restart: always
        volumes:
            - "./db:/var/lib/postgresql/data"
        environment:
            POSTGRES_DB: "nouvelle-db"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "password"
        ports:
            - 5432:5432
